[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 4, y = 0 }
opacity = 0.7
blur = true

[font]
normal = { family = "Roboto Mono", style = "Regular" }
bold = { family = "Roboto Mono", style = "bold" }
italic = { family = "Roboto Mono", style = "italic" }
bold_italic = { family = "Roboto Mono", style = "bold italic" }
size = 18

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
style = { shape = "Beam", blinking = "On" }


[colors.primary]
foreground = "#ffffff" # 白色
background = "#000000" # 黑色

[colors.normal]
black = "#000000"
red = "#ff3b30"
green = "#4cd964"
yellow = "#ffcc00"
blue = "#007aff"
magenta = "#ff2d55"
cyan = "#5ac8fa"
white = "#ffffff"

[colors.bright]
black = "#686868"
red = "#ff3b30"
green = "#4cd964"
yellow = "#ffcc00"
blue = "#007aff"
magenta = "#ff2d55"
cyan = "#5ac8fa"
white = "#ffffff"

[keyboard]
bindings = [
    # 复制 (Cmd + C)
    { key = "C", mods = "Command", action = "Copy" },

    # 粘贴 (Cmd + V)
    { key = "V", mods = "Command", action = "Paste" },

    # 查找 (Cmd + F)
    { key = "F", mods = "Command", action = "SearchForward" },

    # 新建窗口 (Cmd + N)
    { key = "N", mods = "Command", action = "CreateNewWindow" },

    # 缩小字体 (Cmd + -)
    { key = "Minus", mods = "Command", action = "DecreaseFontSize" },

    # 放大字体 (Cmd + =)
    { key = "Equals", mods = "Command", action = "IncreaseFontSize" },

    # 恢复默认字体大小 (Cmd + 0)
    { key = "Key0", mods = "Command", action = "ResetFontSize" },

    # 切换全屏 (Cmd + Enter)
    { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" },

    # 切换到具体标签页 (Cmd + 1 ~ Cmd + 9)
    { key = "Key1", mods = "Command", action = "SelectTab1" },
    { key = "Key2", mods = "Command", action = "SelectTab2" },
    { key = "Key3", mods = "Command", action = "SelectTab3" },
    { key = "Key4", mods = "Command", action = "SelectTab4" },
    { key = "Key5", mods = "Command", action = "SelectTab5" },
    { key = "Key6", mods = "Command", action = "SelectTab6" },
    { key = "Key7", mods = "Command", action = "SelectTab7" },
    { key = "Key8", mods = "Command", action = "SelectTab8" },
    { key = "Key9", mods = "Command", action = "SelectTab9" },

    # 隐藏 Alacritty (Cmd + H)
    { key = "H", mods = "Command", action = "Hide" },

    # 隐藏其他应用 (Cmd + Option + H)
    { key = "H", mods = "Command|Option", action = "HideOtherApplications" },
]

